name       : libspectre
version    : 0.2.9
release    : 5
source     :
    - https://libspectre.freedesktop.org/releases/libspectre-0.2.9.tar.gz : 49ae9c52b5af81b405455c19fe24089d701761da2c45d22164a99576ceedfbed
license    : GPL-2.0-or-later
component  : programming.library
summary    : libspectre is a small library for rendering Postscript documents
description: |
    libspectre is a small library for rendering Postscript documents
builddeps  :
    - pkgconfig(cairo)
    - ghostscript-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
