name       : libspectre
version    : 0.2.8
release    : 2
source     :
    - https://libspectre.freedesktop.org/releases/libspectre-0.2.8.tar.gz : 65256af389823bbc4ee4d25bfd1cc19023ffc29ae9f9677f2d200fa6e98bc7a8
license    : GPL-2.0
component  : programming
summary    : libspectre is a small library for rendering Postscript documents
description: |
    libspectre is a small library for rendering Postscript documents
builddeps  :
    - pkgconfig(cairo)
    - ghostscript-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
